Repository Rushulyte/Fulbank, pull requests merged in 2022-05, with the labels that each got.

#3 :card_file_box: Database v1
  .gitignore
  db/MCD.MCD
  db/MLO.mlo
  db/MLR.mlr
  db/Workspace.ws
  db/fulbank.uml
  db/seeder.sql
Labels: database

#11 :card_file_box: Link database to entities
  .gitignore
  src/Fulbank.sln.DotSettings.user
  src/Fulbank/entities/Database.cs
  src/Fulbank/packages.config
Labels: database, entity, dependencies

#12 :lipstick: Adding UI
  src/Fulbank/Fulbank.csproj
  src/Fulbank/Pages/Home.Designer.cs
  src/Fulbank/Pages/Home.cs
  src/Fulbank/Pages/Home.resx
  src/Fulbank/Pages/Login.Designer.cs
  src/Fulbank/Pages/Login.cs
  src/Fulbank/Pages/Login.resx
  src/Fulbank/Pages/Register.Designer.cs
  src/Fulbank/Pages/Register.cs
  src/Fulbank/Pages/Register.resx
  src/Fulbank/Program.cs
Labels: design

#14 :truck: Move entities
  src/Fulbank/Classes/Database.cs
  src/Fulbank/Classes/Entities/AccountType.cs
  src/Fulbank/Classes/Entities/BankAccount.cs
  src/Fulbank/Classes/Entities/Conversion.cs
  src/Fulbank/Classes/Entities/CryptoCurrency.cs
  src/Fulbank/Classes/Entities/ExternalOperation.cs
  src/Fulbank/Classes/Entities/InternalOperation.cs
  src/Fulbank/Classes/Entities/MoneyInterface.cs
  src/Fulbank/Classes/Entities/Operation.cs
  src/Fulbank/Classes/Entities/User.cs
  src/Fulbank/Classes/Entities/UserType.cs
  src/Fulbank/Classes/Entities/Wallet.cs
Labels: entity

#15 :recycle: Fix mess
  src/APITest/APITest.csproj
  src/APITest/Program.cs
  src/Fulbank/App.config
  src/Fulbank/Classes/Database.cs
  src/Fulbank/Classes/Entities/AccountType.cs
  src/Fulbank/Classes/Entities/BankAccount.cs
  src/Fulbank/Classes/Entities/Conversion.cs
  src/Fulbank/Classes/Entities/CryptoCurrency.cs
  src/Fulbank/Classes/Entities/ExternalOperation.cs
  src/Fulbank/Classes/Entities/InternalOperation.cs
  src/Fulbank/Classes/Entities/MoneyInterface.cs
  src/Fulbank/Classes/Entities/Operation.cs
  src/Fulbank/Classes/Entities/User.cs
  src/Fulbank/Classes/Entities/UserType.cs
  src/Fulbank/Classes/Entities/Wallet.cs
  src/Fulbank/Classes/Meta.cs
  src/Fulbank/Fulbank.csproj
  src/Fulbank/Pages/Home.Designer.cs
  src/Fulbank/Pages/Home.cs
  src/Fulbank/Pages/Home.resx
  src/Fulbank/Pages/Login.Designer.cs
  src/Fulbank/Pages/Login.cs
  src/Fulbank/Pages/Login.resx
  src/Fulbank/Pages/Register.Designer.cs
  src/Fulbank/Pages/Register.cs
  src/Fulbank/Pages/Register.resx
  src/Fulbank/Program.cs
  src/Fulbank/Properties/Resources.Designer.cs
  src/Fulbank/Properties/Resources.resx
  src/Fulbank/Properties/Settings.Designer.cs
  src/Fulbank/Properties/Settings.settings
  src/Fulbank/packages.config
Labels: bug

#17 :sparkles: Adding Unittests Base
  .github/workflows/unittests.yml
  src/Fulbank.sln
  src/Fulbank.sln.DotSettings.user
  src/Unittests/UnitTestBase.cs
  src/Unittests/Unittests.csproj
  src/Unittests/Usings.cs
Labels: unittests

#19 :memo: Add docs
  README.md
  docs/README.md
  docs/pdf/Assignment.pdf
  docs/pdf/Tasks.pdf
Labels: documentation

#23 📝 Add Install Documentation
  .editorconfig
  docs/INSTALL.md
  docs/LINUX.md
  docs/img/access_environment_variable.png
  docs/img/access_path_variable.png
  docs/img/add_path_btn.png
  docs/img/add_path_variable.png
  docs/img/env_variables_link.png
Labels: documentation

#24 :sparkles: Add the database connection form
  docs/INSTALL.md
  src/APITest/APITest.csproj
  src/APITest/Program.cs
  src/Fulbank/App.config
  src/Fulbank/Classes/Entities/AccountType.cs
  src/Fulbank/Classes/Entities/BankAccount.cs
  src/Fulbank/Classes/Entities/Conversion.cs
  src/Fulbank/Classes/Entities/CryptoCurrency.cs
  src/Fulbank/Classes/Entities/ExternalOperation.cs
  src/Fulbank/Classes/Entities/InternalOperation.cs
  src/Fulbank/Classes/Entities/MoneyInterface.cs
  src/Fulbank/Classes/Entities/Operation.cs
  src/Fulbank/Classes/Entities/User.cs
  src/Fulbank/Classes/Entities/UserType.cs
  src/Fulbank/Classes/Entities/Wallet.cs
  src/Fulbank/Classes/Meta.cs
  src/Fulbank/Fulbank.csproj
  src/Fulbank/Pages/Connection.Designer.cs
  src/Fulbank/Pages/Connection.cs
  src/Fulbank/Pages/Connection.resx
  src/Fulbank/Pages/Home.Designer.cs
  src/Fulbank/Pages/Home.cs
  src/Fulbank/Pages/Home.resx
  src/Fulbank/Pages/Login.Designer.cs
  src/Fulbank/Pages/Login.cs
  src/Fulbank/Pages/Login.resx
  src/Fulbank/Pages/Register.Designer.cs
  src/Fulbank/Pages/Register.cs
  src/Fulbank/Pages/Register.resx
  src/Fulbank/Program.cs
  src/Fulbank/Properties/Resources.Designer.cs
  src/Fulbank/Properties/Resources.resx
  src/Fulbank/Properties/Settings.Designer.cs
  src/Fulbank/Properties/Settings.settings
  src/Fulbank/packages.config
Labels: form
